Repository Wave-Play/robo.js, pull requests merged in 2024-11, with the labels that each got.

#344 fix(create-robo/templates): remove `typeRoots` property to prevent interference with default ts behavior
  packages/create-robo/src/env.ts
  packages/create-robo/templates/app-ts-react/tsconfig.json
  packages/create-robo/templates/app-ts/tsconfig.json
  packages/create-robo/templates/webapp-ts-react/tsconfig.json
  templates/discord-activities/react-colyseus-ts/tsconfig.json
  templates/discord-activities/react-multiplayer-video-ts/tsconfig.json
  templates/discord-activities/react-music-proxy-ts/tsconfig.json
  templates/discord-activities/react-tailwind-shadcn-ts/tsconfig.json
  templates/discord-activities/react-tailwind-ts/tsconfig.json
  templates/discord-activities/react-trpc-ts/tsconfig.json
  templates/discord-activities/react-ts/tsconfig.json
  templates/discord-activities/unity/tsconfig.json
  templates/discord-activities/vanilla-ts/tsconfig.json
  templates/discord-bots/analytics-ts/tsconfig.json
  templates/discord-bots/mongodb-ts/tsconfig.json
  templates/discord-bots/mrjawesome-dev-toolkit-ts/tsconfig.json
  templates/discord-bots/mrjawesome-slash-commands-ts/tsconfig.json
  templates/discord-bots/postgres-ts/tsconfig.json
  templates/discord-bots/prisma-ts/tsconfig.json
  templates/discord-bots/purrth-vader-ts/tsconfig.json
  templates/discord-bots/starter-ts/tsconfig.json
  templates/web-apps/react-ts/tsconfig.json
Labels: hacktoberfest-accepted

#337 patch(create-robo): skip discord credentials when setting up with the web kit
  packages/create-robo/src/index.ts
Labels: hacktoberfest

#348 feat(cron): add Cron.get() method for retrieving saved jobs
  packages/@robojs/cron/README.md
  packages/@robojs/cron/src/core/cron.ts
  packages/@robojs/cron/src/events/_start.ts
Labels: enhancement, plugin, hacktoberfest

#350 feat(create-robo): add "Web App" to initial prompt when no kit is there
  packages/create-robo/src/index.ts
Labels: hacktoberfest, hacktoberfest-accepted

#354 Web App template - SvelteKit - Javascript
  templates/web-apps/svelte-js/.gitignore
  templates/web-apps/svelte-js/.npmrc
  templates/web-apps/svelte-js/.prettierignore
  templates/web-apps/svelte-js/.prettierrc
  templates/web-apps/svelte-js/.robo/build/api/get-count.js
  templates/web-apps/svelte-js/.robo/build/api/set-count.js
  templates/web-apps/svelte-js/.robo/build/app.html
  templates/web-apps/svelte-js/.robo/build/routes/+page.svelte
  templates/web-apps/svelte-js/.robo/data/9da9e61fc2a36ffc8ea278b61e89a1ebbd004bdeb99cf8a57768d6a3302bd5de
  templates/web-apps/svelte-js/.robo/data/efe899c74558f20b08bbc19bf0228c0c25bddb7871d80bd34ac8b33c030b3698
  templates/web-apps/svelte-js/.robo/manifest.json
  templates/web-apps/svelte-js/README.md
  templates/web-apps/svelte-js/config/plugins/robojs/server.mjs
  templates/web-apps/svelte-js/config/robo.mjs
  templates/web-apps/svelte-js/config/vite.mjs
  templates/web-apps/svelte-js/example.env
  templates/web-apps/svelte-js/package.json
  templates/web-apps/svelte-js/src/api/get-count.js
  templates/web-apps/svelte-js/src/api/set-count.js
  templates/web-apps/svelte-js/src/app.html
  templates/web-apps/svelte-js/src/routes/+page.svelte
  templates/web-apps/svelte-js/static/favicon.png
  templates/web-apps/svelte-js/static/global.css
  templates/web-apps/svelte-js/svelte.config.js
  templates/web-apps/svelte-js/vite.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#356 SvelteKit TS Template
  templates/web-apps/svelte-ts/.gitignore
  templates/web-apps/svelte-ts/.npmrc
  templates/web-apps/svelte-ts/.prettierignore
  templates/web-apps/svelte-ts/.prettierrc
  templates/web-apps/svelte-ts/.robo/build/api/get-count.js
  templates/web-apps/svelte-ts/.robo/build/api/set-count.js
  templates/web-apps/svelte-ts/.robo/build/app.d.js
  templates/web-apps/svelte-ts/.robo/build/app.html
  templates/web-apps/svelte-ts/.robo/build/lib/index.js
  templates/web-apps/svelte-ts/.robo/build/routes/+page.svelte
  templates/web-apps/svelte-ts/.robo/data/9da9e61fc2a36ffc8ea278b61e89a1ebbd004bdeb99cf8a57768d6a3302bd5de
  templates/web-apps/svelte-ts/.robo/data/efe899c74558f20b08bbc19bf0228c0c25bddb7871d80bd34ac8b33c030b3698
  templates/web-apps/svelte-ts/.robo/manifest.json
  templates/web-apps/svelte-ts/README.md
  templates/web-apps/svelte-ts/config/plugins/robojs/server.mjs
  templates/web-apps/svelte-ts/config/robo.mjs
  templates/web-apps/svelte-ts/config/vite.mjs
  templates/web-apps/svelte-ts/eslint.config.js
  templates/web-apps/svelte-ts/example.env
  templates/web-apps/svelte-ts/package-lock.json
  templates/web-apps/svelte-ts/package.json
  templates/web-apps/svelte-ts/src/api/get-count.ts
  templates/web-apps/svelte-ts/src/api/set-count.ts
  templates/web-apps/svelte-ts/src/app.d.ts
  templates/web-apps/svelte-ts/src/app.html
  templates/web-apps/svelte-ts/src/lib/index.ts
  templates/web-apps/svelte-ts/src/routes/+page.svelte
  templates/web-apps/svelte-ts/static/favicon.png
  templates/web-apps/svelte-ts/static/global.css
  templates/web-apps/svelte-ts/svelte.config.js
  templates/web-apps/svelte-ts/tsconfig.json
  templates/web-apps/svelte-ts/vite.config.js
  templates/web-apps/svelte-ts/vite.config.ts
Labels: hacktoberfest, hacktoberfest-accepted

#366 fix(robo): Getting the custom build directory on start command
  packages/robo/src/cli/commands/start.ts
Labels: hacktoberfest
